### ISSUE TITLE
Add automatic code integration features

### ISSUE THREAD

**Issue by jakeschurch** [samwho/iex-rs#2]
Due to how quickly the IEX repo is expanding, I thought it might be helpful to utilize automated CI capabilities for windows & linux platforms.

- For linux/mac: [travis-ci](https://travis-ci.org/)
- For windows: [appveyor](https://ci.appveyor.com)

If approved, please navigate to travis-ci and setup a project for iex-rs. For some reason, only appveyor will allow me to setup CI for iex-rs.

I can take care of the CI config files & updating README and cargo.toml with badges.

**Comment by samwho** [comment]
Will do this when I get a chance :)

**Comment by jakeschurch** [comment]
*Note - will be committing code through feature/foo branches to a develop branch, that way, we don't have to worry about bugs in the production release [master] branch - and can instead merge to "next release" - development [develop] branch.

**Comment by samwho** [comment]
I just activated this repo on Travis.
